# Generated by Django 3.0.7 on 2020-12-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201230_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='classes',
            name='student_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='section',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.CharField(max_length=32),
        ),
    ]
